services:
  postgres:
    image: postgres
    container_name: webchat_postgres_db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - potsgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  potsgres_data:
